server.servlet.context-path=/LoanTrack-Back-api
spring.application.name=LoanTrack-BackApi
server.port=8013

#Header security
security.headers.key=MDW
security.headers.token=ABC123

# Threads
server.tomcat.threads.max=400
server.tomcat.max-keep-alive-requests=350

# Timeouts RestTemplate
rest.template.connection.timeout=40000
rest.template.connection.request.timeout=20000
rest.template.response.timeout=40000

# Pool RestTemplate
rest.template.pool.max.total=400
rest.template.pool.default.max.per.route=400