spring.application.name=notification-service

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yoonny0130@gmail.com
spring.mail.password=SDFG#WFG&Q@ewq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
