spring.application.name=Credit-product-service
# Puerto del microservicio
server.port=8083

# Configuración de base de datos PostgreSQL (NeonDB con SSL)
spring.datasource.url=jdbc:postgresql://ep-shiny-sunset-a4owzv1p-pooler.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_udwRHl48IAXr
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

